module.exports = {
  "main": "main-2EmuK",
  "bottom": "bottom-qaW5p",
  "content": "content-3-Spa",
  "comments": "comments-U6lN7",
  "menuEntryJumbo": "menuEntryJumbo-1gAPA",
  "tagJumbo": "tagJumbo-2y6Er",
  "indexJumbo": "indexJumbo-3aSGA",
  "appear": "appear-2kyTl",
  "appear-mobile": "appear-mobile-1afEK",
  "park-right": "park-right-2f-ID",
  "all": "all-3amHh",
  "header": "header-3JfGF",
  "bottomLike": "bottomLike-1iw1L",
  "disqus_thread": "disqus_thread-1jnRb",
  "footer": "footer-3r5Xl",
  "zblogowani": "zblogowani-Zrc7Z",
  "logo": "logo-2wc3f",
  "sideMenu": "sideMenu-3RB85",
  "visible": "visible-202JZ",
  "closed": "closed-3xC98"
};