exports = module.exports = require("../../node_modules/css-loader/lib/css-base.js")(undefined);
// imports


// module
exports.push([module.id, ".crumbs-1UWBj{display:flex}.crumbs-1UWBj ul,:not(ol) .crumbs-1UWBj ul,:not(ul) .crumbs-1UWBj ul{list-style-type:none;padding:0;margin:0;display:flex;flex-wrap:wrap;max-width:100%;padding:3rem 0;flex-direction:column}.crumbs-1UWBj ul li,:not(ol) .crumbs-1UWBj ul li,:not(ul) .crumbs-1UWBj ul li{margin:0;padding:0;display:flex;max-width:100%}.crumbs-1UWBj ul li:before,:not(ol) .crumbs-1UWBj ul li:before,:not(ul) .crumbs-1UWBj ul li:before{content:\"\";margin:0;padding:0;font-size:inherit;font-weight:inherit;line-height:inherit;text-align:left;vertical-align:inherit;width:auto;height:auto;position:static;opacity:1}@media only screen and (min-width:836px) and (max-width:1019px){.crumbs-1UWBj ul,:not(ol) .crumbs-1UWBj ul,:not(ul) .crumbs-1UWBj ul{padding:1rem 0}}@media only screen and (min-width:1020px){.crumbs-1UWBj ul,:not(ol) .crumbs-1UWBj ul,:not(ul) .crumbs-1UWBj ul{padding:2rem 0}}@media only screen and (min-width:836px) and (max-width:1019px){.crumbs-1UWBj ul,:not(ol) .crumbs-1UWBj ul,:not(ul) .crumbs-1UWBj ul{flex-direction:row}}@media only screen and (min-width:1020px){.crumbs-1UWBj ul,:not(ol) .crumbs-1UWBj ul,:not(ul) .crumbs-1UWBj ul{flex-direction:row}}.crumbs-1UWBj li{font-family:Roboto Slab,serif;font-weight:300;letter-spacing:-.003rem;font-size:16px;line-height:7rem;padding-top:2.06rem;padding-bottom:4.94rem}.crumbs-1UWBj li:not(:first-child):before{content:\">\";padding:0 2rem}.crumbs-1UWBj a{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.crumbs-1UWBj a:link,.crumbs-1UWBj a:visited{text-decoration:none}.crumbs-1UWBj a:active,.crumbs-1UWBj a:hover{text-decoration:underline}.responsive-13m41 li:not(:first-child),.responsive-13m41 li:not(:first-child):before{display:none}@media only screen and (min-width:836px) and (max-width:1019px){.responsive-13m41 li:not(:first-child),.responsive-13m41 li:not(:first-child):before{display:inline-block}}@media only screen and (min-width:1020px){.responsive-13m41 li:not(:first-child),.responsive-13m41 li:not(:first-child):before{display:inline-block}}", ""]);

// exports
exports.locals = {
	"crumbs": "crumbs-1UWBj",
	"responsive": "responsive-13m41"
};